version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - echo "Skipping tests..."
      - npm run build || echo "No build step, continuing..."

artifacts:
  files:
    - '**/*'
